# Generated by Django 5.2.9 on 2026-01-06 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=100)),
                ('program_name', models.CharField(max_length=50)),
                ('study_mode', models.CharField(choices=[('Online', 'Online'), ('On-Campus', 'On-Campus')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('student', models.ForeignKey(limit_choices_to={'role_title': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
