# Generated by Django 5.2.9 on 2026-01-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
